package de.fhg.aisec.ids.idscp2.drivers.default_driver_impl.daps

import de.fhg.aisec.ids.idscp2.drivers.interfaces.DapsDriver

/**
 * NullDaps for testing purpose only
 */
class NullDaps : DapsDriver {

    override val token: ByteArray
        get() =  "This dummy token is generated by 'NullDAPS' driver! Do not depend on it!".toByteArray()

    override fun verifyToken(dat: ByteArray, securityRequirements: Any?): Long {
        return 100 // DA is always valid for 100 seconds
    }


}