version: '2'
services:

  # Image for TPM simulator
  provider-tpm2dsim:
    image: fhgaisec/tpm2dsim:develop
    volumes:
      - ./camel-ids/socket/:/data/cml/tpm2d/communication/
    command: /tpm2d/cml-tpm2d

  # Image for core platform, gets docker control socket mounted into the image
  provider-core:
    image: fhgaisec/iot-connector:develop
    hostname: provider-core
    volumes:
      - /tmp/ids-provider/log/:/root/data/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./system.properties:/root/etc/system.properties
      - ./provider-client-truststore.jks:/root/etc/client-truststore.jks
      - ./provider-client-keystore.jks:/root/etc/client-keystore.jks
      - ./camel-ids/provider-socket/:/var/run/tpm2d/
      - /root/deploy/
    ports:
      - "5006:5005"
      - "8282:8181"
    networks:
      - ids-wide
      - provider-internal

  # Data App (MQTT consumer, publishes over REST)
  provider-app:
    image: fhgaisec/example-001-client:develop
    networks:
      - provider-internal

  dockergen:
    image: jwilder/docker-gen
    command: -watch /root/tmpl/ids-example-001-provider.xml /root/deploy/ids-example-001-provider.xml
    volumes_from:
      - provider-core
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./ids-example-001-provider.xml:/root/tmpl/ids-example-001-provider.xml

networks:
  ids-wide:
    driver: bridge
  provider-internal:
    driver: bridge
