version: '2'
services:

  # Image for TPM simulator
  consumer-tpm2dsim:
    image: app-store.isst.fraunhofer.de:5000/ids/tpm2dsim:0.1
    volumes:
      - ./camel-ids/socket/:/data/cml/tpm2d/communication/
    command: /tpm2d/cml-tpm2d

  # Image for core platform, gets docker control socket and route definition mounted into the image
  consumer-core:
    image: app-store.isst.fraunhofer.de:5000/ids/core-platform:0.1
    hostname: consumer-core
    volumes:
      - /tmp/ids/log/:/root/data/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./camel-ids/consumersocket/:/var/run/tpm2d/
      - ./consumer-server-keystore.jks:/root/etc/server-keystore.jks
      - ./consumer-server-truststore.jks:/root/etc/server-truststore.jks
      - ./ids-example-001-consumer.xml:/root/deploy/ids-example-001-consumer.xml
    ports:
      - "5005:5005"
      - "9292:9292"
      - "8181:8181"
    environment:
      - "HOST=consumer-core"
    networks:
      - ids-wide
      - consumer-internal

  # Data App (REST consumer, displays web page)
  consumer-app:
    image: app-store.isst.fraunhofer.de:5000/ids/example-001/example-001-server:0.1
    ports:
      - "8081:8081"
    networks:
      - consumer-internal

networks:
  ids-wide:
    driver: bridge
  consumer-internal:
    driver: bridge
