version: '3'
services:

  consumer-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    command: [ "--class-path", "./jars/*", "de.fhg.aisec.ids.TrustedConnector",
               "--spring.config.location=/root/etc/application.yml" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../etc/application.yml:/root/etc/application.yml
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings.mapdb:/root/etc/settings.mapdb
      - ../etc/consumer-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-multipart-server.xml:/root/deploy/example-multipart-server.xml
    ports:
      - "8080:8080"
      - "28282:28282"
    networks:
      - ids-wide
    profiles:
      - server

  provider-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    command: [ "--class-path", "./jars/*", "de.fhg.aisec.ids.TrustedConnector",
               "--spring.config.location=/root/etc/application.yml" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../etc/application.yml:/root/etc/application.yml
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings2.mapdb:/root/etc/settings.mapdb
      - ../etc/provider-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-multipart-client.xml:/root/deploy/example-multipart-client.xml
    ports:
      - "8081:8080"
    networks:
      - ids-wide
    profiles:
      - client

networks:
  ids-wide:
    driver: bridge
