version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  consumer-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - ../log/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../cert-stores/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../cert-stores/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-client-broadcast.xml:/root/deploy/example-idscp2-client.xml
    # Enable this port mappings for debugging or UI access from localhost
#    ports:
#      - "5005:5005"
#      - "8181:8181"
#      - "8443:8443"
    networks:
      - ids-wide

networks:
  ids-wide:
    driver: bridge
