# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attestation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attestation.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x61ttestation.proto\"$\n\x03Pcr\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t\"\xa6\x01\n\x0f\x43ontrollerToTpm\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.ControllerToTpm.Code\x12\"\n\x05\x61type\x18\x02 \x01(\x0e\x32\x13.IdsAttestationType\x12\x16\n\x0equalifyingData\x18\x03 \x01(\t\x12\x0c\n\x04pcrs\x18\x04 \x01(\x05\"$\n\x04\x43ode\x12\x1c\n\x18INTERNAL_ATTESTATION_REQ\x10\x00\"\xe4\x01\n\x0fTpmToController\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.TpmToController.Code\x12\"\n\x05\x61type\x18\x02 \x01(\x0e\x32\x13.IdsAttestationType\x12\x0c\n\x04halg\x18\x03 \x01(\t\x12\x0e\n\x06quoted\x18\x04 \x01(\t\x12\x11\n\tsignature\x18\x05 \x01(\t\x12\x18\n\npcr_values\x18\x06 \x03(\x0b\x32\x04.Pcr\x12\x17\n\x0f\x63\x65rtificate_uri\x18\x07 \x01(\t\"$\n\x04\x43ode\x12\x1c\n\x18INTERNAL_ATTESTATION_RES\x10\x00*6\n\x12IdsAttestationType\x12\t\n\x05\x42\x41SIC\x10\x00\x12\x07\n\x03\x41LL\x10\x01\x12\x0c\n\x08\x41\x44VANCED\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_IDSATTESTATIONTYPE = _descriptor.EnumDescriptor(
  name='IdsAttestationType',
  full_name='IdsAttestationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BASIC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADVANCED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=459,
  serialized_end=513,
)
_sym_db.RegisterEnumDescriptor(_IDSATTESTATIONTYPE)

IdsAttestationType = enum_type_wrapper.EnumTypeWrapper(_IDSATTESTATIONTYPE)
BASIC = 0
ALL = 1
ADVANCED = 2


_CONTROLLERTOTPM_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='ControllerToTpm.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ATTESTATION_REQ', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_CONTROLLERTOTPM_CODE)

_TPMTOCONTROLLER_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='TpmToController.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ATTESTATION_RES', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=421,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_TPMTOCONTROLLER_CODE)


_PCR = _descriptor.Descriptor(
  name='Pcr',
  full_name='Pcr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='Pcr.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Pcr.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=57,
)


_CONTROLLERTOTPM = _descriptor.Descriptor(
  name='ControllerToTpm',
  full_name='ControllerToTpm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='ControllerToTpm.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='atype', full_name='ControllerToTpm.atype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qualifyingData', full_name='ControllerToTpm.qualifyingData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pcrs', full_name='ControllerToTpm.pcrs', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLLERTOTPM_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=226,
)


_TPMTOCONTROLLER = _descriptor.Descriptor(
  name='TpmToController',
  full_name='TpmToController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='TpmToController.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='atype', full_name='TpmToController.atype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='halg', full_name='TpmToController.halg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quoted', full_name='TpmToController.quoted', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='TpmToController.signature', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pcr_values', full_name='TpmToController.pcr_values', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='certificate_uri', full_name='TpmToController.certificate_uri', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TPMTOCONTROLLER_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=457,
)

_CONTROLLERTOTPM.fields_by_name['code'].enum_type = _CONTROLLERTOTPM_CODE
_CONTROLLERTOTPM.fields_by_name['atype'].enum_type = _IDSATTESTATIONTYPE
_CONTROLLERTOTPM_CODE.containing_type = _CONTROLLERTOTPM
_TPMTOCONTROLLER.fields_by_name['code'].enum_type = _TPMTOCONTROLLER_CODE
_TPMTOCONTROLLER.fields_by_name['atype'].enum_type = _IDSATTESTATIONTYPE
_TPMTOCONTROLLER.fields_by_name['pcr_values'].message_type = _PCR
_TPMTOCONTROLLER_CODE.containing_type = _TPMTOCONTROLLER
DESCRIPTOR.message_types_by_name['Pcr'] = _PCR
DESCRIPTOR.message_types_by_name['ControllerToTpm'] = _CONTROLLERTOTPM
DESCRIPTOR.message_types_by_name['TpmToController'] = _TPMTOCONTROLLER
DESCRIPTOR.enum_types_by_name['IdsAttestationType'] = _IDSATTESTATIONTYPE

Pcr = _reflection.GeneratedProtocolMessageType('Pcr', (_message.Message,), dict(
  DESCRIPTOR = _PCR,
  __module__ = 'attestation_pb2'
  # @@protoc_insertion_point(class_scope:Pcr)
  ))
_sym_db.RegisterMessage(Pcr)

ControllerToTpm = _reflection.GeneratedProtocolMessageType('ControllerToTpm', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERTOTPM,
  __module__ = 'attestation_pb2'
  # @@protoc_insertion_point(class_scope:ControllerToTpm)
  ))
_sym_db.RegisterMessage(ControllerToTpm)

TpmToController = _reflection.GeneratedProtocolMessageType('TpmToController', (_message.Message,), dict(
  DESCRIPTOR = _TPMTOCONTROLLER,
  __module__ = 'attestation_pb2'
  # @@protoc_insertion_point(class_scope:TpmToController)
  ))
_sym_db.RegisterMessage(TpmToController)


# @@protoc_insertion_point(module_scope)

