version: '2'
services:

  # TPM trusted third party (RAT repository)
  repository.aisec.fraunhofer.de:
    image: fraunhoferaisec/ttpsim:${dockerTag}
    build:
      context: '../../rat-repository'
    ports:
      - "31337:31337"
    networks:
      - ids-wide

networks:
  ids-wide:
    driver: bridge
