image: maven

stages:
- build
- push

build:
  stage: build
  variables:
    GRADLE_USER_HOME: "/cache/.gradle"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
  - mkdir -p /cache/.gradle
  - apt update && apt install -y openjdk-8-jdk
  script: 
  - ./gradlew --parallel clean install
  artifacts:
    when: always
    paths:
    - "*/target/surefire-reports"
    - "target/site"

# apparently mvn does not push the core-platform image    
push:
  stage: push
  image: docker
  script:
  - docker tag registry.netsec.aisec.fraunhofer.de/ids/core-platform:develop registry.netsec.aisec.fraunhofer.de/ids/core-platform:latest
  - docker push registry.netsec.aisec.fraunhofer.de/ids/core-platform:develop
  - docker push registry.netsec.aisec.fraunhofer.de/ids/core-platform:latest
  only:
    - develop
