language: java
jdk:
  - oraclejdk11
services:
  - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - wget -O protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
  - mkdir $HOME/protoc && unzip -d $HOME/protoc protoc.zip
  - export PATH=$HOME/protoc/bin:$PATH
  - echo $PATH
  - nvm install 12
  - npm install -g yarn  
install: true
script: ./gradlew --parallel clean build
