language: java
jdk:
  - oraclejdk11
services:
  - docker
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
  - sudo apt-get -y install protobuf-compiler
  - nvm install 12
  - npm install -g yarn  
install: true
script: ./gradlew --parallel clean build
