version: '2'
services:

  # TPM simulator
  ids-tpm2dsim:
    image: fraunhoferaisec/tpm2dsim:develop
    volumes:
      - ./camel-ids/socket/:/data/cml/tpm2d/communication/
    command: /tpm2d/cml-tpm2d
    container_name: iot-connector-tpm

  # Trusted third party (RAT repository) simulator
  ids-ttpsim:
    image: fraunhoferaisec/ttpsim:develop
    ports:
      - "31337:31337"
    container_name: iot-connector-ttpsim

  # The core platform, mounts docker control socket into the image
  ids-core:
    image: fraunhoferaisec/iot-connector-core-platform:develop
    tty: true
    stdin_open: true
    volumes:
      - /tmp/ids/log/:/root/data/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./camel-ids/socket/:/var/run/tpm2d/
    container_name: iot-connector
    ports:
      - "5005:5005"
      - "9292:9292"
      - "8181:8181"
      - "8443:8443"
