idscp2: "0.10.2"
ktlint: "0.43.2"

# Pinning
okhttp: "5.0.0-alpha.5"

# Kotlin library/compiler version
kotlin: "1.6.10"
kotlinxCoroutines: "1.5.2"

# The used version of the infomodel from IESE
infomodel: "4.1.0"

# Provided by feature, but required for compilation
jaxbApi: "2.3.1"
# Required for RouteManager metrics tests
jaxbCore: "3.0.2"
jaxbImpl: "3.0.2"
jaxActivation: "1.2.0"

camel: "3.15.0"
influxDB: "2.22"

# Camel ships with cxf, however it is slightly older so we want a newer version
cxf: "3.5.1"

guava: "31.1-jre"
slf4j: "1.7.30"
junit4: "4.13.2"
junit5: "5.8.2"
mockito: "4.4.0"
mapdb: "3.0.8"
jnrunix: "0.38.17"
protobuf: "3.19.4"
httpcore: "4.4.11"
httpclient: "4.5.7"

# Needed for policy reasoning with 2p (formerly tuProlog)
2p: "4.1.1"
commonsText: "1.9"
protonpack: "1.16"
antlr4: "4.9.3"

# Needed for ACME module
acme: "2.12"
nanohttpd: "2.3.1"

# Docker API dependencies
javaxJson: "1.1.4"
dockerJavaApi: "0.0.13"

# We will pull in a newer version of jackson because of security fixes
jackson: "2.13.2"

orgJson: "20210307"

# Needed for camel multipart processor
commonsFileUpload: "1.4"

# Needed for info model manager
commonsCli: "1.5.0"
javaxValidation: "2.0.1.Final"

# Needed for web console
auth0Jwt: "3.19.0"
swagger: "1.6.5"
jose4j: "0.7.11"

springBoot: "2.6.4"
bouncyCastle: "1.70"