idscp2: "0.4.3"
ktlint: "0.41.0"

# Pinning
okhttp: "4.9.1"

# Kotlin library/compiler version
kotlin: "1.4.32"
kotlinxCoroutines: "1.4.3"
# basically, the first requirement, all other libraries depend on this version
karaf: "4.2.10"
# Jetty version should fit bundled version in karaf
jetty: "9.4.30.v20200611"

# The used version of the infomodel from IESE
infomodel: "4.0.0"

pax: "7.2.14"
# Provided by feature, but required for compilation
jaxbApi: "2.3.1"
# Required for RouteManager metrics tests
jaxbCore: "2.3.0.1"
jaxbImpl: "2.3.3"
jaxActivation: "1.2.0"

# Starting with camel 3.1.0, XML dump features and metrics have been removed!
camel: "3.0.1"
camelHttp4: "3.0.0-M4"
camelZeroMQ: "2.22.0"
influxDB: "2.14"

# Camel ships with cxf, however it is slightly older so we want a newer version
cxf: "3.3.4"

# OSGI libraries
osgiCompendium: "6.0.0"
osgi: "6.0.0"
felixFramework: "5.6.10"

ahc: "2.4.9"
checkerQual: "2.5.2"
guava: "30.1-jre"
slf4j: "1.7.30"
junit4: "4.13.2"
mockito: "3.8.0"
mapdb: "3.0.7"
# jnrunix and jnrffi must be consistent
jnrunix: "0.22"
jnrffi: "2.1.5"
protobuf: "3.15.5"
httpcore: "4.4.11"
httpclient: "4.5.7"
jaxwsApi: "2.3.1"

# Needed for policy reasoning with 2p (formerly tuProlog)
2p: "4.1.1"
commonsText: "1.9"
protonpack: "1.15"
antlr4: "4.7.2"

# Needed for ACME module
acme: "2.3"
nanohttpd: "2.3.1"

# Docker API dependencies
javaxJson: "1.1.4"
dockerJavaApi: "0.0.11"

# We will pull in a newer version of jackson because of security fixes
jackson: "2.12.0"

# Needed for camel multipart processor
commonsFileUpload: "1.4"

# Needed for rat-repository, should be seperated
jersey: "2.26"
sqliteJdbc: "3.30.1"
gson: "2.7"

# Needed for info model manager
commonsCli: "1.4"
javaxValidation: "2.0.1.Final"

# Needed for token manager to assemble JWTs
jsonwebtoken: "0.11.2"
jose4j: "0.7.6"

# Needed for web console
javaxServlet: "4.0.1"
wsRsApi: "2.1"
auth0Jwt: "3.8.2"
swagger: "1.5.18"

# Required for PaxExam integration tests
paxExam: "4.13.3"
# 4.x versions of awaitility are not supported because of old ServiceMix Hamcrest version
awaitility: "3.1.6"
servicemixHamcrest: "1.3_1"
javaxAnnotation: "1.3.2"

springBoot: "2.4.5"
bouncyCastle: "1.68"