idscp2: "0.9.0"
ktlint: "0.43.2"

# Pinning
okhttp: "4.9.1"

# Kotlin library/compiler version
kotlin: "1.6.10"
kotlinxCoroutines: "1.5.2"

# The used version of the infomodel from IESE
infomodel: "4.1.0"

# Provided by feature, but required for compilation
jaxbApi: "2.3.1"
# Required for RouteManager metrics tests
jaxbCore: "2.3.0.1"
jaxbImpl: "2.3.3"
jaxActivation: "1.2.0"

camel: "3.14.0"
camelHttp4: "3.0.0-M4"
influxDB: "2.14"

# Camel ships with cxf, however it is slightly older so we want a newer version
cxf: "3.3.4"

ahc: "2.4.9"
checkerQual: "2.5.2"
guava: "30.1-jre"
slf4j: "1.7.30"
junit4: "4.13.2"
mockito: "3.8.0"
mapdb: "3.0.7"
# jnrunix and jnrffi must be consistent
jnrunix: "0.22"
jnrffi: "2.1.5"
protobuf: "3.19.1"
httpcore: "4.4.11"
httpclient: "4.5.7"

# Needed for policy reasoning with 2p (formerly tuProlog)
2p: "4.1.1"
commonsText: "1.9"
protonpack: "1.15"
antlr4: "4.7.2"

# Needed for ACME module
acme: "2.3"
nanohttpd: "2.3.1"

# Docker API dependencies
javaxJson: "1.1.4"
dockerJavaApi: "0.0.11"

# We will pull in a newer version of jackson because of security fixes
jackson: "2.13.0"

# Needed for camel multipart processor
commonsFileUpload: "1.4"

# Needed for info model manager
commonsCli: "1.4"
javaxValidation: "2.0.1.Final"

# Needed for web console
auth0Jwt: "3.8.2"
swagger: "1.5.18"
jose4j: "0.7.6"

springBoot: "2.5.8"
bouncyCastle: "1.68"