idscp2: "0.11.1"
ktlint: "0.46.1"

# Kotlin library/compiler version
kotlin: "1.7.10"
kotlinxCoroutines: "1.6.4"
# HTTP client
ktor: "2.1.0"

# The used version of the infomodel from IESE
infomodel: "4.1.0"

# Provided by feature, but required for compilation
jaxbApi: "2.4.0-b180830.0359"
# Required for RouteManager metrics tests
jaxbImpl: "4.0.0"
jaxActivation: "1.2.0"

camel: "3.18.1"
influxDB: "2.23"

# Camel ships with cxf, however it is slightly older so we want a newer version
cxf: "3.5.3"

guava: "31.1-jre"
slf4j: "2.0.0"
junit4: "4.13.2"
junit5: "5.9.0"
mockito: "4.7.0"
mapdb: "3.0.8"
jnrunix: "0.38.17"
protobuf: "3.21.5"
httpcore: "4.4.15"
httpclient: "4.5.13"

# Needed for policy reasoning with 2p (formerly tuProlog)
2p: "4.1.1"
commonsText: "1.9"
protonpack: "1.16"

# Needed for ACME module
acme: "2.14"
nanohttpd: "2.3.1"

# Docker API dependencies
javaxJson: "1.1.4"
dockerJavaApi: "0.0.13"

# We will pull in a newer version of jackson because of security fixes
jackson: "2.13.3"

orgJson: "20220320"

# Needed for camel multipart processor
commonsFileUpload: "1.4"

# Needed for info model manager
commonsCli: "1.5.0"
javaxValidation: "2.0.1.Final"

# Needed for web console
auth0Jwt: "3.19.1"
swagger: "1.6.6"
jose4j: "0.7.12"

springBoot: "2.7.3"
bouncyCastle: "1.70"