rootProject.name = "trusted-connector-core"

include(":camel-idscp2-osgi")
include(":camel-influxdb")
include(":camel-multipart-processor")
include(":cxf-jaxws-patch")
include(":examples")
include(":ids-acme")
include(":ids-api")
include(":ids-container-manager")
include(":ids-dataflow-control")
include(":ids-dynamic-tls")
include(":ids-endpoint-config")
include(":ids-infomodel-manager")
include(":ids-route-manager")
include(":ids-settings")
include(":ids-webconsole")
include(":jnr-unixsocket-wrapper")
include(":karaf-assembly")
include(":karaf-features-ids")
