version: '3'
services:

  # Base image for other JDK-based images
  jdk-base:
    image: fraunhoferaisec/jdk-base:${DOCKER_BUILD_TAG:-develop}
    build:
      context: '../docker-jdk-base'
      args:
        BASE_IMAGE: ${BASE_IMAGE:-adoptopenjdk:11-jdk-hotspot}

  # Trusted Connector build container
  build-container:
    image: fraunhoferaisec/docker-build:${DOCKER_BUILD_TAG:-develop}
    build:
      context: '../docker-build'
      args:
        JDK_BASE_IMAGE: fraunhoferaisec/jdk-base:${DOCKER_BUILD_TAG:-develop}

  # Trusted Connector core platform
  core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    build:
      context: '../karaf-assembly'
      args:
        JDK_BASE_IMAGE: fraunhoferaisec/jdk-base:${DOCKER_BUILD_TAG:-develop}

#  # TPM simulator
#  tpmsim:
#    image: fraunhoferaisec/tpmsim:${EXAMPLE_TAG:-develop}
#    build:
#      context: '../examples/tpmsim'