version: '3'
services:

  # Trusted Connector build container
  build-container:
    image: fraunhoferaisec/docker-build:${DOCKER_BUILD_TAG:-develop}
    build:
      context: '../docker-build'

  # Trusted Connector core platform
  core:
    image: fraunhoferaisec/trusted-connector-core:${DOCKER_BUILD_TAG:-develop}
    build:
      context: '../ids-connector'