version: '2'
services:

  # Trusted Connector build container
  build-container:
    image: fraunhoferaisec/docker-build:jdk11
    tty: true
    stdin_open: true
    environment:
      - 'PROJECT_DIR=/core-platform'
      - 'GRADLE_DIR=/.gradle'
      - 'M2_DIR=/.m2'
      - 'JAVA_HOME=/usr/local/openjdk-11'
    volumes:
      - ..:/core-platform
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gradle:/.gradle
      - ~/.m2:/.m2
    build:
      context: '.'