version: '3'
services:

  # Trusted Connector build container
  build-container:
    image: fraunhoferaisec/docker-build:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    environment:
      - 'PROJECT_DIR=/core-platform'
      - 'GRADLE_DIR=/.gradle'
      - 'M2_DIR=/.m2'
    volumes:
      - ..:/core-platform
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gradle:/.gradle
      - ~/.m2:/.m2
    build:
      context: '.'
      args:
        PLATFORM: ${PLATFORM:-amd64}
        BASE_IMAGE: ${BASE_IMAGE:-debian:buster-slim}