%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Prolog representation of a data flow policy
%   
%   Source: example
% 	
%	Do not edit this file, it has been generated automatically
% 	by XText/Xtend.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Only required for SWI-Prolog
% Allow the following predicates to be scattered around the prolog file.
% Otherwise Prolog will issue a warning if they are not stated in subsequent lines.		
%:- discontiguous service/1.
%:- discontiguous rule/1.
%:- discontiguous has_capability/2.
%:- discontiguous has_property/3.
%:- discontiguous has_target/2.
%:- discontiguous requires_prerequisites/2.
%:- discontiguous has_alternativedecision/2.
%:- discontiguous has_obligation/2.
%:- discontiguous receives_label/1.
%%%%%%%% Rules %%%%%%%%%%%%
% I am a test rule of prio 1
rule(testRule).
rule_priority(testRule, 1).
has_target(testRule, allIdsServices).
receives_label(testRule).
has_obligation(testRule, obl2).
has_decision(testRule, allow).

rule(dropLog).
rule_priority(dropLog, 1).
has_target(dropLog, allLogServices).
receives_label(dropLog) :- label(public).
has_decision(dropLog, drop).




%%%%% Services %%%%%%%%%%%%
service(allIdsServices).
has_endpoint(allIdsServices, "^ids.*").
creates_label(allIdsServices, [public]).
has_property(allIdsServices,trustLevel,platform).

service(allLogServices).
has_endpoint(allLogServices, "^log.*").
creates_label(allLogServices, [public]).
has_property(allLogServices,trustLevel,platform).
