version: '3'
services:

  # TPM trusted third party (RAT repository)
  ids-ttpsim:
    image: fraunhoferaisec/ttpsim:${EXAMPLE_TAG:-develop}
    # Enable this port mapping to access TTP from outside the ids-wide network
#    ports:
#      - "31337:31337"
    networks:
      ids-wide:
        aliases:
          - repository.aisec.fraunhofer.de

networks:
  ids-wide:
    driver: bridge
