version: '2'
services:

  # TPM simulator
  ids-tpmsim:
    image: fraunhoferaisec/tpmsim:develop
    volumes:
      - ../tpmsim/tpmsim_data/swtpm:/swtpm/
      - ../tpmsim/tpmsim_data/cml:/data/cml
    build:
      context: '../tpmsim'
    networks:
      - example-internal

  # Trusted third party (RAT repository) simulator
  repository.aisec.fraunhofer.de:
    image: fraunhoferaisec/ttpsim:develop
    build:
      context: '../../rat-repository'
    ports:
      - "31337:31337"
    networks:
      - example-internal

  # The core platform, mounts docker control socket into the image
  example-core:
    image: fraunhoferaisec/trusted-connector-core:develop
    tty: true
    stdin_open: true
    volumes:
      - /tmp/ids/log/:/root/data/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../tpmsim/rootCA.crt:/root/etc/rootca-cert.pem
      - ./example-idscp-localloop.xml:/root/deploy/example-idscp-localloop.xml
    environment:
      - TPM_HOST=ids-tpmsim
    ports:
      - "5005:5005"
      - "9292:9292"
      - "8181:8181"
      - "8443:8443"
    networks:
      example-internal:
        aliases:
          - consumer-core

networks:
  example-internal:
    driver: bridge