version: '2'
services:

  # TPM simulator
  ids-tpmsim:
    image: fraunhoferaisec/tpmsim:develop
    build:
      context: '../tpmsim'
    volumes:
      - ../tpmsim/tpmsim_data.tar:/tpmsim_data.tar
    networks:
      - example-internal

  # Trusted third party (RAT repository) simulator
  ids-ttpsim:
    image: fraunhoferaisec/ttpsim:develop
    build:
      context: '../../rat-repository'
    networks:
      example-internal:
        aliases:
          - repository.aisec.fraunhofer.de

  # The core platform, mounts docker control socket into the image
  ids-core:
    image: fraunhoferaisec/trusted-connector-core:develop
    build:
      context: '../../karaf-assembly'
    tty: true
    stdin_open: true
    volumes:
      - ../log/:/root/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./system.properties:/root/etc/system.properties
      - ../tpmsim/rootCA.crt:/root/etc/rootca-cert.pem
      - ../cert-stores/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../cert-stores/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ../cert-stores/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp-localloop.xml:/root/deploy/example-idscp-localloop.xml
    environment:
      - TPM_HOST=ids-tpmsim
    ports:
      - "5005:5005"
      - "9292:9292"
      - "8181:8181"
      - "8443:8443"
    networks:
      example-internal:
        aliases:
          - consumer-core

networks:
  example-internal:
    driver: bridge