version: '2'
services:

  # TPM simulator
  ids-tpmsim:
    image: fraunhoferaisec/tpmsim:${dockerTag}
    volumes:
      - ../tpmsim/tpmsim_data/swtpm:/swtpm/
      - ../tpmsim/tpmsim_data/cml:/data/cml
    build:
      context: '../tpmsim'
    networks:
      - example-internal
    container_name: iot-connector-tpm

  # Trusted third party (RAT repository) simulator
  ids-ttpsim:
    image: fraunhoferaisec/ttpsim:${dockerTag}
    ports:
      - "31337:31337"
    container_name: iot-connector-ttpsim

  # The core platform, mounts docker control socket into the image
  ids-core:
    image: fraunhoferaisec/trusted-connector-core:${dockerTag}
    tty: true
    stdin_open: true
    volumes:
      - /tmp/ids/log/:/root/data/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tpm2d/:/var/run/tpm2d/
    container_name: iot-connector
    ports:
      - "5005:5005"
      - "9292:9292"
      - "8181:8181"
      - "8443:8443"
