version: '3'
services:

  tc-core-server:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../etc/application.yml:/root/etc/application.yml
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings.mapdb:/root/etc/settings.mapdb
      - ../etc/server-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-server.xml:/root/deploy/example-idscp2-server.xml
      - ./make-contract.xml:/root/deploy/make-contract.xml
    ports:
      - "8080:8080"
    networks:
      - ids-wide
    profiles:
      - server

  tc-core-client:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../etc/application.yml:/root/etc/application.yml
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings2.mapdb:/root/etc/settings.mapdb
      - ../etc/client-keystore.p12:/root/etc/keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-client.xml:/root/deploy/example-idscp2-client.xml
    ports:
      - "8081:8080"
    networks:
      - ids-wide
      - provider-internal
    profiles:
      - client

  echo-server:
    image: jmalloc/echo-server@sha256:c461e7e54d947a8777413aaf9c624b4ad1f1bac5d8272475da859ae82c1abd7d
    environment:
      PORT: "80"
      LOG_HTTP_HEADERS: 1
      LOG_HTTP_BODY: 1
    networks:
      - provider-internal
    profiles:
      - client

networks:
  ids-wide:
    driver: bridge
  provider-internal:
    driver: bridge
