package de.fhg.aisec.ids.idscp2.default_drivers.daps

import de.fhg.aisec.ids.idscp2.idscp_core.drivers.DapsDriver

/**
 * NullDaps for testing purpose only
 */
class NullDaps : DapsDriver {

    override val token: ByteArray
        get() =  "This dummy token is generated by 'NullDAPS' driver! Do not depend on it!".toByteArray()

    override fun verifyToken(dat: ByteArray): Long {
        return 100 // DA is always valid for 100 seconds
    }
}