version: '3'
services:

  ids-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    command: [ "--class-path", "./jars/*", "de.fhg.aisec.ids.TrustedConnector",
               "--spring.config.location=/root/etc/application.yml" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../etc/application.yml:/root/etc/application.yml
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings.mapdb:/root/etc/settings.mapdb
      - ../etc/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../etc/provider-keystore.p12:/root/etc/provider-keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ../etc/tls.properties:/root/etc/tls.properties
      - ./example-idscp2-localloop.xml:/root/deploy/example-idscp2-localloop.xml
    ports:
      - "8080:8080"
    environment:
      TC_DAPS_URL: "https://daps-dev.aisec.fraunhofer.de/v4"
    networks:
      example-internal:
        aliases:
          - consumer-core
          - provider-core

networks:
  example-internal:
    driver: bridge