logging:
  level:
    root: info
#    de.fhg.aisec: debug
    # Use for IDSCP2 debugging
#    de.fhg.aisec.ids.idscp2: trace
#    de.fhg.aisec.ids.camel.idscp2: trace

spring:
  web:
    resources:
      static-locations: classpath:/www/

connector:
  # Used as default for IDSCP2 DAPS instances which have not been explicitly configured.
  daps-url: ${TC_DAPS_URL:}
  # Used for IDS Messages issuerConnector field.
  connector-url: ${TC_CH_ISSUER_CONNECTOR:}
  # Used for IDS Messages senderAgent field.
  sender-agent: ${TC_CH_AGENT:}