version: '3'
services:

  # The core platform, mounts docker control socket and route definition into the image
  consumer-core:
    image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
    tty: true
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../deploy/allow-all-flows.pl:/root/deploy/allow-all-flows.pl
      - ../etc/settings2.mapdb:/root/etc/settings.mapdb
      - ../etc/consumer-keystore.p12:/root/etc/consumer-keystore.p12
      - ../etc/truststore.p12:/root/etc/truststore.p12
      - ./example-idscp2-client.xml:/root/deploy/example-idscp2-client.xml
    # Enable this port mappings for debugging or UI access from localhost
#    ports:
#      - "5005:5005"
#      - "8181:8181"
#      - "8443:8443"
    networks:
      - ids-wide
      - provider-internal

  echo-server:
    image: jmalloc/echo-server@sha256:c461e7e54d947a8777413aaf9c624b4ad1f1bac5d8272475da859ae82c1abd7d
    networks:
      - provider-internal

networks:
  ids-wide:
    driver: bridge
  provider-internal:
    driver: bridge
