version: '2'
services:

  # Image for TPM trusted third party (RAT repository)
  provider-ttpsim:
    image: fraunhoferaisec/ttpsim:example-010
    ports:
      - "31337:31337"
    networks:
      - ids-wide

networks:
  ids-wide:
    driver: bridge
