name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: 3.x
      - name: Build
        run: |
          ./gradlew --parallel yarnBuild check build
